package broker

import (
	"fmt"
	"strings"
)

// This file parses a `show current-config` capture into the units export and
// import act on. Like scripts.go it is pure -- no transport, no I/O -- so it is
// golden-testable against a real capture, which is the discipline internal/render
// follows.
//
// The shape it parses is the broker's own, observed from a real
// `show current-config all` (broker 10.26.0.8827):
//
//	 ! BEGIN                                       <- note the leading space
//	! Command: "show current-config all"
//	! Generated by:
//	!   SEMP Schema Version: "broker/10.26.0.8827" <- `broker/` software, `app/` appliance
//	!   Redacted: "False"
//	! pragma:interpreter:relaxed-db-restore
//
//	home
//	enable
//	configure
//
//	! Create All: "Message Vpns"                   <- a section comment
//	create message-vpn "acme"
//	  exit
//
//	! Configure System:                            <- broker-level sections
//	system scaling  scale  max-connections 1000 ...
//	...
//	! END
//
// Four properties of that shape drive the parser, and each one is a trap that
// cost a real bug before it was pinned by a test:
//
//   - Block boundaries come from INDENTATION, never from matching `exit`. A
//     block's own `exit` sits one level DEEPER than its opener (`authentication`
//     at indent 2 closes with `exit` at indent 4; `message-vpn` at indent 0 closes
//     with `exit` at indent 2), so finding the outermost one would need a full
//     nesting parse and a miscount would merge two objects with no error anywhere.
//   - Operands are QUOTED AND MAY CONTAIN SPACES. A real capture creates the VPN
//     "A VPN WITH LONG NAME AND SPACES" and a queue whose name runs to 200
//     characters of prose. Splitting an opener on whitespace fragments those into
//     several fields and silently renames the object to its first word, so the
//     opener is tokenised quote-aware instead.
//   - A `! pragma:...` line sits at column 0, and appears BOTH between an opener
//     and its indented children AND between a section comment and its opener. So a
//     column-0 comment must not end a block, and a pragma seen before an opener
//     has to be held and attached to it -- `ignore-already-exists` is what lets a
//     `create` line be replayed, so losing it changes what the artifact does.
//   - Broker-level configuration is mostly FLAT column-0 one-liners
//     (`ssl tls-session-timeout 86400`), not blocks with children. A one-liner is
//     just a Block whose Lines has length one.
//
// This tool's own markers (see annotate.go) live in a reserved `! solace-util`
// namespace. They are metadata: never a section, never a boundary, never block
// content. Region and section spans are read from them when present and inferred
// when absent, so a raw broker capture and a marked artifact both parse.

// BrokerType distinguishes a software broker from an appliance. It is read from
// the capture header's SEMP schema version and, for a target, from the live
// broker -- import refuses a cross-type artifact, because an appliance capture
// carries interface, VRF, DNS, clock and SNMP sections with no software
// equivalent and a software capture carries none of them.
type BrokerType string

const (
	BrokerSoftware  BrokerType = "software"
	BrokerAppliance BrokerType = "appliance"
	BrokerUnknown   BrokerType = ""
)

// Region is the part of a capture a block belongs to. `show current-config all`
// emits them in a fixed order -- the mode preamble, a pass that creates every
// message-VPN empty, the broker-level configuration, then each VPN's own objects
// -- and the boundaries matter because `--broker-only` must exclude the
// create-VPN pass, not merely the per-VPN region.
type Region string

const (
	RegionPreamble  Region = "preamble"
	RegionVPNCreate Region = "vpn-create"
	RegionBroker    Region = "broker"
	RegionVPN       Region = "vpn"
)

// Block is one top-level object or one-liner in a captured configuration: the
// column-0 opener plus every indented line that follows it, up to the next
// column-0 opener. Attribute lines are carried verbatim and never interpreted --
// only the opener is parsed, and only far enough to classify the block.
type Block struct {
	Section string   // the broker's own `! Configure X` / `! Create X` comment, without the `! `
	Region  Region   // which part of the capture this block is in
	Index   int      // 1-based position in the capture; also the apply order
	Kind    string   // first token of the opener, `no` and `create` stripped: "message-vpn", "service"
	Name    string   // the object's own quoted operand, "" for a bare one-liner or a scope-only opener
	VPN     string   // the `message-vpn "X"` qualifier, "" when broker-level
	Create  bool     // the opener began with `create`
	Negate  bool     // the opener began with `no`
	Lines   []string // held pragmas + opener + children, verbatim
}

// Omission is one broker-level section that export removed from the artifact
// because import would never apply it. It is recorded IN the artifact so the file
// says what it does not contain -- an absence a reader can see, rather than one
// they have to notice.
type Omission struct {
	Section string
	Reason  string
}

// Capture is a parsed `show current-config` artifact.
type Capture struct {
	Preamble   []string // everything up to and including `configure`, verbatim
	Blocks     []Block
	Omitted    []Omission        // sections export removed; see omitAtExport
	Type       BrokerType
	Version    string            // the header's Version, e.g. "10.26.0.8827"
	SEMPSchema string            // the header's SEMP Schema Version, e.g. "broker/10.26.0.8827"
	Redacted   bool              // a redacted capture cannot be imported
	Meta       map[string]string // this tool's own `! solace-util-meta:` fields, empty for a raw capture
	Marked     bool              // true when the artifact carries our markers
}

// Opener returns the block's command line -- the column-0 line the block was
// built from.
//
// It is NOT Lines[0]. A pragma sitting between a section comment and an opener
// is held and prepended (see parseBody), so Lines[0] is a `! pragma:` comment for
// exactly the `create` blocks that carry one. Reading Lines[0] as the opener made
// those blocks parse as unrecognised and be skipped silently, which is why this
// accessor exists rather than every caller re-deriving it.
func (b Block) Opener() string {
	for _, line := range b.Lines {
		if t := strings.TrimSpace(line); t != "" && !strings.HasPrefix(t, "!") {
			return line
		}
	}
	return ""
}

// VPNs returns the message-VPNs the capture describes, in first-seen order.
func (c *Capture) VPNs() []string {
	var out []string
	seen := map[string]bool{}
	for _, b := range c.Blocks {
		if b.VPN != "" && !seen[b.VPN] {
			seen[b.VPN] = true
			out = append(out, b.VPN)
		}
	}
	return out
}

// SyslogNames lists the syslog entries a capture configures, in first-seen order.
//
// It reads them off the parsed blocks (Kind "syslog", created) rather than by
// matching the line text, so the quote-aware opener tokeniser is what extracts the
// name -- the same code that already survives a name containing spaces.
//
// Import needs this about the TARGET: a `create syslog` cannot be replayed onto a
// broker that already has that entry, and the `no syslog` that would clear it first
// is itself an error when the entry does not exist. Knowing which names are actually
// there is the only way to emit the removal exactly when it is valid.
func (c *Capture) SyslogNames() []string {
	var out []string
	seen := map[string]bool{}
	for _, b := range c.Blocks {
		if b.Kind != kindSyslog || b.Name == "" || seen[b.Name] {
			continue
		}
		seen[b.Name] = true
		out = append(out, b.Name)
	}
	return out
}

// ParseBlocks parses a capture. It refuses an artifact with no `! END`, because
// that terminator is the only evidence the capture is complete: `show
// current-config` writes to stdout and a truncated transfer produces a file that
// is still valid CLI and would import a partial configuration reporting success.
func ParseBlocks(out []byte) (*Capture, error) {
	lines := splitLines(out)
	c := &Capture{Meta: map[string]string{}}

	i := parseHeader(c, lines)
	if err := parseBody(c, lines[i:]); err != nil {
		return nil, err
	}
	return c, nil
}

// splitLines splits on \n and strips a trailing \r, so a capture that crossed a
// Windows host parses identically to one that did not.
func splitLines(out []byte) []string {
	raw := strings.Split(string(out), "\n")
	lines := make([]string, len(raw))
	for i, l := range raw {
		lines[i] = strings.TrimRight(l, "\r")
	}
	return lines
}

// parseHeader reads the comment header and the mode preamble, returning the index
// of the first line after `configure`. The preamble is kept verbatim because every
// script this tool applies needs it, and the broker's own wording is the wording
// known to work.
func parseHeader(c *Capture, lines []string) int {
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		c.Preamble = append(c.Preamble, line)

		if strings.HasPrefix(trimmed, "!") {
			if isMarker(trimmed) {
				readMarker(c, trimmed)
			} else {
				readHeaderField(c, trimmed)
			}
			continue
		}
		// `configure` ends the preamble: everything after it is sections and blocks.
		// Matching on it rather than on a line count is what makes the parser work on
		// a capture whose header has more or fewer metadata lines than the one it was
		// written against.
		if trimmed == "configure" {
			return i + 1
		}
	}
	return len(lines)
}

// readHeaderField pulls the fields import needs out of one broker header comment.
// The values are quoted, so the quotes are stripped; anything unrecognised is
// ignored rather than refused, since the broker is free to add metadata lines.
func readHeaderField(c *Capture, line string) {
	body := strings.TrimSpace(strings.TrimPrefix(line, "!"))
	key, value, ok := strings.Cut(body, ":")
	if !ok {
		return
	}
	value = strings.Trim(strings.TrimSpace(value), `"`)
	switch strings.TrimSpace(key) {
	case "Version":
		c.Version = value
	case "SEMP Schema Version":
		c.SEMPSchema = value
		c.Type = brokerTypeFromSchema(value)
	case "Redacted":
		c.Redacted = strings.EqualFold(value, "true")
	}
}

// brokerTypeFromSchema maps a SEMP schema version onto a broker type.
//
// The prefix is the discriminator, and there are two generations of it:
// `broker/A.B.C.D` and `app/A.B.C.D` from 10.25.4 on, and before that
// `soltr/A_B_C` for an appliance with a `VMR` suffix for software. An
// unrecognised prefix yields BrokerUnknown rather than a guess -- import refuses
// an unknown type instead of assuming the common case, because assuming
// "software" for an appliance capture is exactly the cross-type import the
// refusal exists to prevent.
func brokerTypeFromSchema(schema string) BrokerType {
	prefix, rest, ok := strings.Cut(schema, "/")
	if !ok {
		return BrokerUnknown
	}
	switch prefix {
	case "broker":
		return BrokerSoftware
	case "app":
		return BrokerAppliance
	case "soltr":
		if strings.HasSuffix(rest, "VMR") {
			return BrokerSoftware
		}
		return BrokerAppliance
	}
	return BrokerUnknown
}

// parseBody walks the sections and blocks after the preamble.
func parseBody(c *Capture, lines []string) error {
	var (
		section string
		region  Region
		cur     *Block
		pending []string // pragmas seen before an opener, held for it
		ended   bool
	)

	flush := func() {
		if cur != nil {
			cur.Lines = trimTrailingBlank(cur.Lines)
			c.Blocks = append(c.Blocks, *cur)
			cur = nil
		}
	}

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		switch {
		case trimmed == "":
			// A blank line is not a boundary -- the next column-0 opener is. Blanks
			// between blocks are dropped and blanks inside one are kept, so a golden does
			// not depend on the broker's blank-line habits.
			if cur != nil {
				cur.Lines = append(cur.Lines, line)
			}

		case trimmed == "! END":
			flush()
			ended = true

		case isMarker(trimmed):
			// Our own namespace: metadata only. Never a section, never a boundary.
			flush()
			readMarker(c, trimmed)
			if r, ok := markerRegion(trimmed); ok {
				region = r
			}
			if s, ok := markerSection(trimmed); ok {
				section = s
			}

		case isPragma(trimmed):
			// Absorbed, never a boundary. A pragma appears in two places: between an
			// opener and its indented children (so it must not split the block), and
			// between a section comment and its opener (so it must be HELD and attached
			// to the block that follows). Dropping the held case would lose
			// `ignore-already-exists` from exactly the `create` lines it exists for.
			if cur != nil {
				cur.Lines = append(cur.Lines, line)
			} else {
				pending = append(pending, line)
			}

		case strings.HasPrefix(trimmed, "!"):
			flush()
			section = sectionName(trimmed)

		case isIndented(line):
			if cur == nil {
				// An indented line with no opener means the capture began mid-block, which
				// only a truncated or hand-edited artifact does. Refusing beats silently
				// dropping configuration.
				return fmt.Errorf("malformed capture: indented line %q has no preceding object", trimmed)
			}
			cur.Lines = append(cur.Lines, line)

		default:
			flush()
			b := newBlock(section, len(c.Blocks)+1, line)
			b.Region = regionFor(region, b)
			b.Lines = append(pending, b.Lines...)
			pending = nil
			cur = &b
		}
	}
	flush()

	if !ended {
		return fmt.Errorf("capture is missing its `! END` terminator, so it is truncated or " +
			"incomplete; re-take the export rather than importing a partial configuration")
	}
	return nil
}

// sectionName strips the `! ` and any trailing `:` from a broker section comment,
// leaving the name the classification table is keyed on.
func sectionName(trimmed string) string {
	body := strings.TrimSpace(strings.TrimPrefix(trimmed, "!"))
	return strings.TrimSpace(strings.TrimSuffix(body, ":"))
}

// regionFor decides which region a block belongs to.
//
// A marked artifact says so explicitly and is believed. A raw broker capture does
// not, so the region is inferred from the block itself: anything carrying a VPN
// qualifier is VPN work, a bare `create message-vpn` is the create-VPN pass that
// `--broker-only` must exclude, and everything else is broker-level.
func regionFor(marked Region, b Block) Region {
	if marked != "" {
		return marked
	}
	switch {
	case b.Kind == "message-vpn" && b.Create:
		return RegionVPNCreate
	case b.VPN != "":
		return RegionVPN
	default:
		return RegionBroker
	}
}

// newBlock parses one opener into a Block. The grammar is
// `[no] [create] <kind> ["<name>"] [message-vpn "<vpn>"] ...` and everything past
// that is left in Lines untouched.
// kindMsgVPN is the opener kind that both names an object and scopes one.
const kindMsgVPN = "message-vpn"

// kindSyslog is the opener kind of a syslog logging destination.
const kindSyslog = "syslog"

func newBlock(section string, index int, opener string) Block {
	b := Block{Section: section, Index: index, Lines: []string{opener}}

	toks := tokenizeOpener(opener)
	// `no` and `create` are prefixes on the same command, not the command itself.
	// Stripping both is what lets a caller gate on Kind == "service" and see the
	// whole sandwich -- `service smf shutdown` AND `no service smf shutdown` -- which
	// is the difference between preserving a service's enablement state and flipping it.
	for len(toks) > 0 && !toks[0].quoted {
		if toks[0].text == "no" {
			b.Negate = true
		} else if toks[0].text == "create" {
			b.Create = true
		} else {
			break
		}
		toks = toks[1:]
	}
	if len(toks) == 0 {
		return b
	}
	b.Kind = toks[0].text

	// A `message-vpn "X"` block IS the VPN, so its own name is the qualifier. Without
	// this the VPN-scope filter would keep every VPN's objects but drop the VPN itself.
	if b.Kind == kindMsgVPN {
		b.Name = firstQuoted(toks[1:])
		b.VPN = b.Name
		return b
	}

	// The VPN qualifier is found before the name, because its operand must not be
	// mistaken for the object's own: `message-spool message-vpn "acme"` names no
	// object, and reporting Name == "acme" there would make a scope-only opener look
	// like an object called after its own VPN.
	//
	// operands is everything after the kind and strictly before the qualifier, so
	// the qualifier's own value is out of reach by construction rather than by an
	// index comparison -- which is where this went wrong once already.
	vpn, at := vpnQualifier(toks)
	b.VPN = vpn
	operands := toks[1:]
	if at >= 0 {
		operands = toks[1:at]
	}
	b.Name = firstQuoted(operands)
	return b
}

// token is one opener word, with whether it arrived quoted -- which is what
// separates an operand from a keyword of the same spelling.
type token struct {
	text   string
	quoted bool
}

// tokenizeOpener splits an opener into tokens, treating a double-quoted run as ONE
// token however many spaces it contains.
//
// This is the fix for the bug that mattered most: a real capture creates the VPN
// "A VPN WITH LONG NAME AND SPACES" and queues whose names run to 200 characters
// of prose, and a whitespace split renamed them to "A" -- silently, since the
// result is still a valid-looking name. There is no escape handling because the
// CLI has no way to put a `"` inside a quoted operand, and validVPNName refuses
// one on the way out.
func tokenizeOpener(s string) []token {
	var (
		toks []token
		i    int
	)
	for i < len(s) {
		switch {
		case s[i] == ' ' || s[i] == '\t':
			i++
		case s[i] == '"':
			j := strings.IndexByte(s[i+1:], '"')
			if j < 0 {
				// Unterminated quote: take the rest verbatim rather than dropping it, so a
				// malformed line is visible downstream instead of silently shortened.
				toks = append(toks, token{text: s[i+1:], quoted: true})
				return toks
			}
			toks = append(toks, token{text: s[i+1 : i+1+j], quoted: true})
			i += j + 2
		default:
			j := strings.IndexAny(s[i:], " \t")
			if j < 0 {
				toks = append(toks, token{text: s[i:]})
				return toks
			}
			toks = append(toks, token{text: s[i : i+j]})
			i += j
		}
	}
	return toks
}

// firstQuoted returns the first quoted operand, or "" if there is none. A bare
// one-liner such as `ssl crime-exploit-protection` has none, and "" is the right
// answer for it.
func firstQuoted(toks []token) string {
	for _, t := range toks {
		if t.quoted {
			return t.text
		}
	}
	return ""
}

// vpnQualifier returns the VPN named by a `message-vpn "X"` qualifier and the
// index of the `message-vpn` keyword, or ("", -1).
//
// This is what makes VPN scope work at all: VPN-scoped objects are NOT nested
// inside the message-vpn block. They are separate column-0 blocks carrying the
// qualifier -- `client-username "app1" message-vpn "acme"` -- so the qualifier is
// the only thing that says which VPN an object belongs to. The search starts past
// the kind so that a `message-vpn "acme"` opener is not read as its own qualifier.
func vpnQualifier(toks []token) (string, int) {
	for i := 1; i < len(toks)-1; i++ {
		if !toks[i].quoted && toks[i].text == kindMsgVPN && toks[i+1].quoted {
			return toks[i+1].text, i
		}
	}
	return "", -1
}

// isPragma reports whether a comment is an interpreter pragma. Pragmas are
// significant -- `ignore-already-exists` is what lets a `create` line be replayed
// -- so they travel with their block rather than being dropped as comments.
func isPragma(trimmed string) bool {
	return strings.HasPrefix(strings.TrimSpace(strings.TrimPrefix(trimmed, "!")), "pragma:")
}

// isIndented reports whether a line belongs to the block above it.
func isIndented(line string) bool {
	return line != "" && (line[0] == ' ' || line[0] == '\t')
}

// trimTrailingBlank drops the blank lines a block collected before the next opener.
func trimTrailingBlank(lines []string) []string {
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}
	return lines
}
