package broker

import (
	"strings"
	"testing"
)

// driver_test.go covers internal/broker/driver.go: the generated apply script and
// the marker protocol it reports back through.
//
// Both halves are pure, so everything here runs without a broker -- which matters,
// because this script is the thing that actually applies configuration to a
// production broker and there is no second code path a test could exercise instead.

// TestRenderDriverExactOutput pins the whole generated script for one chunk.
//
// It is deliberately an exact-match assertion rather than a set of Contains checks.
// This text is shell that runs inside a production broker with the operator's whole
// configuration in it: a stray quote, a lost `trap`, or a heredoc that stops quoting
// are not things to discover in production, and each of them changes this string.
func TestRenderDriverExactOutput(t *testing.T) {
	got, err := renderDriver([]chunk{{
		Name: `teardown A VPN WITH SPACES`,
		Body: "home\nenable\nconfigure\n" + `no message-vpn "A VPN WITH SPACES"` + "\n",
	}}, "/usr/sw/jail/cliscripts", "/usr/sw/loads/currentload/bin/cli")
	if err != nil {
		t.Fatalf("renderDriver: %v", err)
	}

	want := `#!/bin/sh
# Generated by ` + "`solace-util broker perform import-config`" + `. Do not edit.
# Applies each chunk through the broker's own ` + "`source script ... stop-on-error`" + `,
# checks the transcript tail, and reports one marker line per chunk.
set -u

CLIDIR='/usr/sw/jail/cliscripts'
CLI='/usr/sw/loads/currentload/bin/cli'
WRAPPER='solace-util-run'
TMP="$CLIDIR/.solace-util-chunk-out"

cleanup() {
  rm -f "$TMP" "$CLIDIR/$WRAPPER" "$CLIDIR/solace-util-chunk-000"
}
trap cleanup EXIT INT TERM

# ---- chunk 0: teardown A VPN WITH SPACES ----
cat > "$CLIDIR/solace-util-chunk-000" <<'SOLACE_UTIL_CHUNK_EOF'
home
enable
configure
no message-vpn "A VPN WITH SPACES"
SOLACE_UTIL_CHUNK_EOF
printf 'source script solace-util-chunk-000 stop-on-error no-prompt\n' > "$CLIDIR/$WRAPPER"
"$CLI" -Apes "$WRAPPER" > "$TMP" 2>&1
if tail -n 10 "$TMP" | grep -qiE 'invalid command|error:|command not found|busy'; then
  echo 'SOLACE-UTIL-DETAIL-BEGIN'
  tail -n 10 "$TMP"
  echo 'SOLACE-UTIL-DETAIL-END'
  echo 'SOLACE-UTIL-CHUNK-FAIL 0'
  exit 1
fi
echo 'SOLACE-UTIL-CHUNK-OK 0'

echo 'SOLACE-UTIL-DONE'
`
	if got != want {
		t.Errorf("renderDriver output differs.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestRenderDriverQuotesChunkBodiesLiterally is the property the heredoc exists for:
// a configuration line full of shell metacharacters must reach the broker byte for
// byte. A capture carries `$`, backticks and quotes inside object names and
// passwords, and an unquoted heredoc would EXPAND them -- silently applying
// something other than what was captured.
func TestRenderDriverQuotesChunkBodiesLiterally(t *testing.T) {
	body := "create client-username \"$USER`whoami`\" message-vpn \"acme\"\n  password \"a'b\\\"c$(id)\"\n"
	got, err := renderDriver([]chunk{{Name: "vpn", Body: body}}, "/d", "/cli")
	if err != nil {
		t.Fatalf("renderDriver: %v", err)
	}
	if !strings.Contains(got, body) {
		t.Errorf("the chunk body was not written through verbatim:\n%s", got)
	}
	if !strings.Contains(got, "<<'"+heredocDelim+"'") {
		t.Error("the heredoc delimiter must be QUOTED, or the shell expands the configuration")
	}
}

// TestRenderDriverRefusesABodyCarryingTheDelimiter covers the one input that would
// break the quoting: a chunk containing the delimiter would close its own heredoc
// and the rest of the configuration would be executed as shell. Refusing is right --
// nothing in `show current-config` output looks like this, so an artifact that does
// is not what it claims to be.
func TestRenderDriverRefusesABodyCarryingTheDelimiter(t *testing.T) {
	_, err := renderDriver([]chunk{{Name: "evil", Body: "x\n" + heredocDelim + "\nrm -rf /\n"}}, "/d", "/cli")
	if err == nil {
		t.Fatal("renderDriver accepted a body containing its own heredoc delimiter")
	}
	if !strings.Contains(err.Error(), heredocDelim) {
		t.Errorf("err = %v, want it to name the delimiter", err)
	}
}

// TestRenderDriverCleansUpEveryChunk pins the trap. A failed or interrupted import
// must not leave the artifact's configuration -- credentials and all -- sitting in
// the broker's cliscripts directory.
func TestRenderDriverCleansUpEveryChunk(t *testing.T) {
	got, err := renderDriver([]chunk{{Name: "a", Body: "a\n"}, {Name: "b", Body: "b\n"}}, "/d", "/cli")
	if err != nil {
		t.Fatalf("renderDriver: %v", err)
	}
	if !strings.Contains(got, "trap cleanup EXIT INT TERM") {
		t.Error("no trap: an interrupted import would leave configuration in the broker")
	}
	for _, want := range []string{`"$CLIDIR/solace-util-chunk-000"`, `"$CLIDIR/solace-util-chunk-001"`, `"$TMP"`} {
		if !strings.Contains(got, "rm -f") || !strings.Contains(got, want) {
			t.Errorf("cleanup does not remove %s:\n%s", want, got)
		}
	}
}

// TestRenderDriverSanitisesChunkNamesInComments covers the one place a chunk name
// (which is a message-VPN name, so operator-controlled) reaches the shell text. A
// newline there would end the comment and run the remainder as code.
func TestRenderDriverSanitisesChunkNamesInComments(t *testing.T) {
	got, err := renderDriver([]chunk{{Name: "evil\nrm -rf /", Body: "x\n"}}, "/d", "/cli")
	if err != nil {
		t.Fatalf("renderDriver: %v", err)
	}
	if strings.Contains(got, "# ---- chunk 0: evil\nrm -rf /") {
		t.Errorf("a newline in a chunk name escaped its comment:\n%s", got)
	}
	if !strings.Contains(got, "# ---- chunk 0: evil?rm -rf / ----") {
		t.Errorf("the name should be sanitised in place, got:\n%s", got)
	}
}

// TestParseDriverOutputOutcomes covers the marker protocol, including every way it
// can be wrong.
//
// Strictness is the whole point. This parse is how an import learns whether anything
// worked, so an ambiguous reading must be an ERROR: output that stops early, a
// marker naming a chunk that was never sent, or no markers at all would each
// otherwise be read as "fine" and certify an import that did not happen.
func TestParseDriverOutputOutcomes(t *testing.T) {
	chunks := []chunk{{Name: "one"}, {Name: "two"}}

	cases := []struct {
		name     string
		out      string
		wantErr  string
		wantLen  int
		wantOK   []bool
		wantDetl string
	}{
		{
			name:    "every chunk applied",
			out:     "SOLACE-UTIL-CHUNK-OK 0\nSOLACE-UTIL-CHUNK-OK 1\nSOLACE-UTIL-DONE\n",
			wantLen: 2,
			wantOK:  []bool{true, true},
		},
		{
			// A failing chunk stops the driver, so there is legitimately no
			// completion marker here -- this must NOT read as truncation.
			name: "a chunk failed, with detail",
			out: "SOLACE-UTIL-CHUNK-OK 0\n" +
				"SOLACE-UTIL-DETAIL-BEGIN\nerror: bad command\nSOLACE-UTIL-DETAIL-END\n" +
				"SOLACE-UTIL-CHUNK-FAIL 1\n",
			wantLen:  2,
			wantOK:   []bool{true, false},
			wantDetl: "error: bad command",
		},
		{
			name:    "output cut short after a success",
			out:     "SOLACE-UTIL-CHUNK-OK 0\n",
			wantErr: "cut short",
		},
		{
			name:    "no markers at all",
			out:     "sh: /usr/sw/jail/.solace-util-import: not found\n",
			wantErr: "no chunk markers at all",
		},
		{
			name:    "a marker naming a chunk that does not exist",
			out:     "SOLACE-UTIL-CHUNK-OK 0\nSOLACE-UTIL-CHUNK-OK 7\nSOLACE-UTIL-DONE\n",
			wantErr: "not one of the",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := parseDriverOutput([]byte(tc.out), chunks)
			if tc.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), tc.wantErr) {
					t.Fatalf("err = %v, want it to mention %q", err, tc.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("parseDriverOutput: %v", err)
			}
			if len(got) != tc.wantLen {
				t.Fatalf("got %d result(s), want %d: %+v", len(got), tc.wantLen, got)
			}
			for i, ok := range tc.wantOK {
				if got[i].OK != ok {
					t.Errorf("result[%d].OK = %v, want %v", i, got[i].OK, ok)
				}
				if got[i].Index != i || got[i].Name != chunks[i].Name {
					t.Errorf("result[%d] = %+v, want index %d named %q", i, got[i], i, chunks[i].Name)
				}
			}
			if tc.wantDetl != "" && got[len(got)-1].Detail != tc.wantDetl {
				t.Errorf("Detail = %q, want %q -- a failed chunk with no detail is not actionable",
					got[len(got)-1].Detail, tc.wantDetl)
			}
		})
	}
}

// TestParseDriverOutputDetectsGapsAndDuplicates covers what the terminator alone
// cannot: a run that ends with SOLACE-UTIL-DONE is not proof every chunk was
// reported, only that the driver reached its last line. A marker dropped or
// reordered somewhere in the MIDDLE still leaves the last result intact and the
// terminator present, so this has to be checked separately from truncation -- and
// missing it matters: a dropped OK for a TEARDOWN chunk means the report omits a
// VPN that was actually destroyed.
func TestParseDriverOutputDetectsGapsAndDuplicates(t *testing.T) {
	cases := []struct {
		name    string
		chunks  []chunk
		out     string
		wantErr string
	}{
		{
			// The terminator arrives, but only 2 of the 3 given chunks ever reported.
			name:    "terminator after fewer results than chunks",
			chunks:  []chunk{{Name: "one"}, {Name: "two"}, {Name: "three"}},
			out:     "SOLACE-UTIL-CHUNK-OK 0\nSOLACE-UTIL-CHUNK-OK 1\nSOLACE-UTIL-DONE\n",
			wantErr: "reported 2 chunk result(s) but was given 3",
		},
		{
			// Chunk 1's marker never arrived and chunk 2's did: a gap, not a
			// truncation -- the run still ends with a terminator, so the count
			// mismatch is what catches it.
			name:    "a gap between reported chunks",
			chunks:  []chunk{{Name: "one"}, {Name: "two"}, {Name: "three"}},
			out:     "SOLACE-UTIL-CHUNK-OK 0\nSOLACE-UTIL-CHUNK-OK 2\nSOLACE-UTIL-DONE\n",
			wantErr: "reported 2 chunk result(s) but was given 3",
		},
		{
			// Chunk 0's marker arrived twice and chunk 1's never did. The count
			// happens to match here (2 results, 2 chunks), so this is the case
			// that exercises the per-position check rather than the count check.
			name:    "a duplicated chunk marker",
			chunks:  []chunk{{Name: "one"}, {Name: "two"}},
			out:     "SOLACE-UTIL-CHUNK-OK 0\nSOLACE-UTIL-CHUNK-OK 0\nSOLACE-UTIL-DONE\n",
			wantErr: "chunk 0 where chunk 1 was expected",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := parseDriverOutput([]byte(tc.out), tc.chunks)
			if err == nil || !strings.Contains(err.Error(), tc.wantErr) {
				t.Fatalf("err = %v, want it to mention %q", err, tc.wantErr)
			}
		})
	}
}

// TestParseDriverOutputSuccessCarriesNoDetail pins the credential rule from the
// other side: a successful chunk's transcript never leaves the broker, so no result
// for one may carry transcript text.
func TestParseDriverOutputSuccessCarriesNoDetail(t *testing.T) {
	got, err := parseDriverOutput(
		[]byte("SOLACE-UTIL-DETAIL-BEGIN\nsomething\nSOLACE-UTIL-DETAIL-END\nSOLACE-UTIL-CHUNK-OK 0\nSOLACE-UTIL-DONE\n"),
		[]chunk{{Name: "one"}})
	if err != nil {
		t.Fatalf("parseDriverOutput: %v", err)
	}
	if got[0].Detail != "" {
		t.Errorf("a SUCCESSFUL chunk carried transcript detail %q; only a failure may", got[0].Detail)
	}
}

// TestKeywordPatternEscapesEachPhrase guards the grep the whole failure check rests
// on: a phrase reaching grep -E unescaped would be read as a pattern, so a keyword
// containing a metacharacter would silently match the wrong thing (or nothing).
func TestKeywordPatternEscapesEachPhrase(t *testing.T) {
	got := keywordPattern()
	for _, k := range failKeywords {
		if !strings.Contains(got, strings.ReplaceAll(k, ".", `\.`)) {
			t.Errorf("pattern %q does not carry keyword %q", got, k)
		}
	}
	if strings.Count(got, "|") != len(failKeywords)-1 {
		t.Errorf("pattern %q should alternate exactly %d phrases", got, len(failKeywords))
	}
}

// TestShQuoteHandlesASingleQuote covers the one case POSIX single-quoting cannot do
// naively: there is no escape character inside single quotes, so an embedded quote
// has to close, escape and reopen.
func TestShQuoteHandlesASingleQuote(t *testing.T) {
	if got, want := shQuote(`it's`), `'it'\''s'`; got != want {
		t.Errorf("shQuote(`it's`) = %s, want %s", got, want)
	}
}
